declare meiro{
   input map_value_arg0[BIT],map_value_arg1[BIT],map_value_arg2[BIT],map_value_arg3[BIT],map_value_arg4[BIT],map_value_arg5[BIT],map_value_arg6[BIT],map_value_arg7[BIT],map_value_arg8[BIT],map_value_arg9[BIT]
                  ,map_value_arg10[BIT],map_value_arg11[BIT],map_value_arg12[BIT],map_value_arg13[BIT],map_value_arg14[BIT],map_value_arg15[BIT],map_value_arg16[BIT],map_value_arg17[BIT],map_value_arg18[BIT],map_value_arg19[BIT]
                  ,map_value_arg20[BIT],map_value_arg21[BIT],map_value_arg22[BIT],map_value_arg23[BIT],map_value_arg24[BIT],map_value_arg25[BIT],map_value_arg26[BIT],map_value_arg27[BIT],map_value_arg28[BIT],map_value_arg29[BIT]
                  ,map_value_arg30[BIT],map_value_arg31[BIT],map_value_arg32[BIT],map_value_arg33[BIT],map_value_arg34[BIT],map_value_arg35[BIT],map_value_arg36[BIT],map_value_arg37[BIT],map_value_arg38[BIT],map_value_arg39[BIT]
                  ,map_value_arg40[BIT],map_value_arg41[BIT],map_value_arg42[BIT],map_value_arg43[BIT],map_value_arg44[BIT],map_value_arg45[BIT],map_value_arg46[BIT],map_value_arg47[BIT],map_value_arg48[BIT],map_value_arg49[BIT]
                  ,map_value_arg50[BIT],map_value_arg51[BIT],map_value_arg52[BIT],map_value_arg53[BIT],map_value_arg54[BIT],map_value_arg55[BIT],map_value_arg56[BIT],map_value_arg57[BIT],map_value_arg58[BIT],map_value_arg59[BIT]
                  ,map_value_arg60[BIT],map_value_arg61[BIT],map_value_arg62[BIT],map_value_arg63[BIT],map_value_arg64[BIT],map_value_arg65[BIT],map_value_arg66[BIT],map_value_arg67[BIT],map_value_arg68[BIT],map_value_arg69[BIT]
                  ,map_value_arg70[BIT],map_value_arg71[BIT],map_value_arg72[BIT],map_value_arg73[BIT],map_value_arg74[BIT],map_value_arg75[BIT],map_value_arg76[BIT],map_value_arg77[BIT],map_value_arg78[BIT],map_value_arg79[BIT]
                  ,map_value_arg80[BIT],map_value_arg81[BIT],map_value_arg82[BIT],map_value_arg83[BIT],map_value_arg84[BIT],map_value_arg85[BIT],map_value_arg86[BIT],map_value_arg87[BIT],map_value_arg88[BIT],map_value_arg89[BIT]
                 , map_value_arg90[BIT],map_value_arg91[BIT],map_value_arg92[BIT],map_value_arg93[BIT],map_value_arg94[BIT],map_value_arg95[BIT],map_value_arg96[BIT],map_value_arg97[BIT],map_value_arg98[BIT],map_value_arg99[BIT]
                 , map_value_arg100[BIT],map_value_arg101[BIT],map_value_arg102[BIT],map_value_arg103[BIT],map_value_arg104[BIT],map_value_arg105[BIT],map_value_arg106[BIT],map_value_arg107[BIT],map_value_arg108[BIT],map_value_arg109[BIT]
                 , map_value_arg110[BIT],map_value_arg111[BIT],map_value_arg112[BIT],map_value_arg113[BIT],map_value_arg114[BIT],map_value_arg115[BIT],map_value_arg116[BIT],map_value_arg117[BIT],map_value_arg118[BIT],map_value_arg119[BIT]
                 , map_value_arg120[BIT],map_value_arg121[BIT],map_value_arg122[BIT],map_value_arg123[BIT],map_value_arg124[BIT],map_value_arg125[BIT],map_value_arg126[BIT],map_value_arg127[BIT];
   output  kekka_out0[BIT],kekka_out1[BIT],kekka_out2[BIT],kekka_out3[BIT],kekka_out4[BIT],kekka_out5[BIT],kekka_out6[BIT],kekka_out7[BIT],kekka_out8[BIT],kekka_out9[BIT],
                     kekka_out10[BIT],kekka_out11[BIT],kekka_out12[BIT],kekka_out13[BIT],kekka_out14[BIT],kekka_out15[BIT],kekka_out16[BIT],kekka_out17[BIT],kekka_out18[BIT],kekka_out19[BIT],
                     kekka_out20[BIT],kekka_out21[BIT],kekka_out22[BIT],kekka_out23[BIT],kekka_out24[BIT],kekka_out25[BIT],kekka_out26[BIT],kekka_out27[BIT],kekka_out28[BIT],kekka_out29[BIT],
                     kekka_out30[BIT],kekka_out31[BIT],kekka_out32[BIT],kekka_out33[BIT],kekka_out34[BIT],kekka_out35[BIT],kekka_out36[BIT],kekka_out37[BIT],kekka_out38[BIT],kekka_out39[BIT],
                     kekka_out40[BIT],kekka_out41[BIT],kekka_out42[BIT],kekka_out43[BIT],kekka_out44[BIT],kekka_out45[BIT],kekka_out46[BIT],kekka_out47[BIT],kekka_out48[BIT],kekka_out49[BIT],
                     kekka_out50[BIT],kekka_out51[BIT],kekka_out52[BIT],kekka_out53[BIT],kekka_out54[BIT],kekka_out55[BIT],kekka_out56[BIT],kekka_out57[BIT],kekka_out58[BIT],kekka_out59[BIT]
                    ;
   func_in in_do(map_value_arg0,map_value_arg1,map_value_arg2,map_value_arg3,map_value_arg4,map_value_arg5,map_value_arg6,map_value_arg7,map_value_arg8,map_value_arg9,
                  map_value_arg10,map_value_arg11,map_value_arg12,map_value_arg13,map_value_arg14,map_value_arg15,map_value_arg16,map_value_arg17,map_value_arg18,map_value_arg19,
                  map_value_arg20,map_value_arg21,map_value_arg22,map_value_arg23,map_value_arg24,map_value_arg25,map_value_arg26,map_value_arg27,map_value_arg28,map_value_arg29,
                  map_value_arg30,map_value_arg31,map_value_arg32,map_value_arg33,map_value_arg34,map_value_arg35,map_value_arg36,map_value_arg37,map_value_arg38,map_value_arg39,
                  map_value_arg40,map_value_arg41,map_value_arg42,map_value_arg43,map_value_arg44,map_value_arg45,map_value_arg46,map_value_arg47,map_value_arg48,map_value_arg49,
                  map_value_arg50,map_value_arg51,map_value_arg52,map_value_arg53,map_value_arg54,map_value_arg55,map_value_arg56,map_value_arg57,map_value_arg58,map_value_arg59,
                  map_value_arg60,map_value_arg61,map_value_arg62,map_value_arg63,map_value_arg64,map_value_arg65,map_value_arg66,map_value_arg67,map_value_arg68,map_value_arg69,
                  map_value_arg70,map_value_arg71,map_value_arg72,map_value_arg73,map_value_arg74,map_value_arg75,map_value_arg76,map_value_arg77,map_value_arg78,map_value_arg79,
                  map_value_arg80,map_value_arg81,map_value_arg82,map_value_arg83,map_value_arg84,map_value_arg85,map_value_arg86,map_value_arg87,map_value_arg88,map_value_arg89,
                  map_value_arg90,map_value_arg91,map_value_arg92,map_value_arg93,map_value_arg94,map_value_arg95,map_value_arg96,map_value_arg97,map_value_arg98,map_value_arg99,
                  map_value_arg100,map_value_arg101,map_value_arg102,map_value_arg103,map_value_arg104,map_value_arg105,map_value_arg106,map_value_arg107,map_value_arg108,map_value_arg109,
                  map_value_arg110,map_value_arg111,map_value_arg112,map_value_arg113,map_value_arg114,map_value_arg115,map_value_arg116,map_value_arg117,map_value_arg118,map_value_arg119,
                  map_value_arg120,map_value_arg121,map_value_arg122,map_value_arg123,map_value_arg124,map_value_arg125,map_value_arg126,map_value_arg127
                  );
   func_out end_meiro(kekka_out0,kekka_out1,kekka_out2,kekka_out3,kekka_out4,kekka_out5,kekka_out6,kekka_out7,kekka_out8,kekka_out9,
                     kekka_out10,kekka_out11,kekka_out12,kekka_out13,kekka_out14,kekka_out15,kekka_out16,kekka_out17,kekka_out18,kekka_out19,
                     kekka_out20,kekka_out21,kekka_out22,kekka_out23,kekka_out24,kekka_out25,kekka_out26,kekka_out27,kekka_out28,kekka_out29,
                     kekka_out30,kekka_out31,kekka_out32,kekka_out33,kekka_out34,kekka_out35,kekka_out36,kekka_out37,kekka_out38,kekka_out39,
                     kekka_out40,kekka_out41,kekka_out42,kekka_out43,kekka_out44,kekka_out45,kekka_out46,kekka_out47,kekka_out48,kekka_out49,
                     kekka_out50,kekka_out51,kekka_out52,kekka_out53,kekka_out54,kekka_out55,kekka_out56,kekka_out57,kekka_out58,kekka_out59
                     );

    }
