declare subs{
	input data_in17[BIT],data_in19[BIT],data_in21[BIT],data_in23[BIT],data_in25[BIT],data_in27[BIT],data_in29[BIT],
data_in33[BIT],data_in35[BIT],data_in37[BIT],data_in39[BIT],data_in41[BIT],data_in43[BIT],data_in45[BIT],
data_in49[BIT],data_in51[BIT],data_in53[BIT],data_in55[BIT],data_in57[BIT],data_in59[BIT],data_in61[BIT],
data_in65[BIT],data_in67[BIT],data_in69[BIT],data_in71[BIT],data_in73[BIT],data_in75[BIT],data_in77[BIT],
data_in81[BIT],data_in83[BIT],data_in85[BIT],data_in87[BIT],data_in89[BIT],data_in91[BIT],data_in93[BIT],
data_in97[BIT],data_in99[BIT],data_in101[BIT],data_in103[BIT],data_in105[BIT],data_in107[BIT],data_in109[BIT],
data_index17[BIT],data_index19[BIT],data_index21[BIT],data_index23[BIT],data_index25[BIT],data_index27[BIT],data_index29[BIT],
data_index33[BIT],data_index35[BIT],data_index37[BIT],data_index39[BIT],data_index41[BIT],data_index43[BIT],data_index45[BIT],
data_index49[BIT],data_index51[BIT],data_index53[BIT],data_index55[BIT],data_index57[BIT],data_index59[BIT],data_index61[BIT],
data_index65[BIT],data_index67[BIT],data_index69[BIT],data_index71[BIT],data_index73[BIT],data_index75[BIT],data_index77[BIT],
data_index81[BIT],data_index83[BIT],data_index85[BIT],data_index87[BIT],data_index89[BIT],data_index91[BIT],data_index93[BIT],
data_index97[BIT],data_index99[BIT],data_index101[BIT],data_index103[BIT],data_index105[BIT],data_index107[BIT],data_index109[BIT];
	output sub_array_out[BIT];
	func_in subs_exe(
                    
data_index17,data_index19,data_index21,data_index23,data_index25,data_index27,data_index29,
data_index33,data_index35,data_index37,data_index39,data_index41,data_index43,data_index45,
data_index49,data_index51,data_index53,data_index55,data_index57,data_index59,data_index61,
data_index65,data_index67,data_index69,data_index71,data_index73,data_index75,data_index77,
data_index81,data_index83,data_index85,data_index87,data_index89,data_index91,data_index93,
data_index97,data_index99,data_index101,data_index103,data_index105,data_index107,data_index109,

data_in17,data_in19,data_in21,data_in23,data_in25,data_in27,data_in29,
data_in33,data_in35,data_in37,data_in39,data_in41,data_in43,data_in45,
data_in49,data_in51,data_in53,data_in55,data_in57,data_in59,data_in61,
data_in65,data_in67,data_in69,data_in71,data_in73,data_in75,data_in77,
data_in81,data_in83,data_in85,data_in87,data_in89,data_in91,data_in93,
data_in97,data_in99,data_in101,data_in103,data_in105,data_in107,data_in109);
}
